from components.ai import HostileEnemy, RangedEnemy, DragonEnemy, SummonedAlly
from components import consumable
from components.battler import Battler
from components.inventory import Inventory, Bag_Inventory
from components.level import Level
from components.equipment import Equipment
from components.equippable import Equippable
from entity import Actor, Item, Stairs, Shop, Enchant, Bag
from equipment_slots import EquipmentSlots
import copy
import os
import colors

player = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.green),
    color = (255, 255, 255),
    name = "Derpity",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Fighter", strength = 18, dexterity = 14, constitution = 16,
                      intelligence = 10, wisdom = 14, charisma = 5,
                      feats_to_take = 2, gold = 0),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 0),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player0.png'),
    graphic_pos = (0, 112),
)
orc = Actor(
    char = "o",
    tile_code = 11337,
    color = (63, 127, 63),
    name = "Orc",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Warrior", strength = 17, dexterity = 11, constitution = 12,
                      intelligence = 8, wisdom = 7, charisma = 6, cr = 0.5),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 1),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player1.png'),
    graphic_pos = (16, 12*16),
)
goblin = Actor(
    char = "g",
    tile_code = 11329,
    color = (0, 127, 0),
    name = "Goblin",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Warrior", strength = 11, dexterity = 13, constitution = 12,
                      intelligence = 10, wisdom = 9, charisma = 6, cr = 0.4, size = "Small"),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 1),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player1.png'),
    graphic_pos = (0, 12*16),
)
red_dragon_young = Actor(
    char = "D",
    tile_code = 10974,
    tile_colors = (colors.white, colors.red),
    color = (200, 0, 0),
    name = "Young Red Dragon",
    ai_cls = DragonEnemy,
    battler = Battler(hit_dice = "Dragon", strength = 25, dexterity = 10, constitution = 17,
                      intelligence = 12, wisdom = 13, charisma = 12, base_na = 12,
                      cr = 7, size = "Large",
                      full_attack = [['P', 'claws', 1, 6],['P', 'claws', 1, 6],['S', 'bites', 1, 6],
                                     ['S', 'buffets', 1, 6],['S', 'buffets', 1, 6],['S', 'slaps', 1, 8]],
                      spells = {'Cone Fire Breath': [6, 10]}),
    # Tail slap is a secondary attack (-5 to hit) but 1.5*str bonus to damage.  Need to accomodate]),),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 13),
    graphic = os.path.join('Dawnlike', 'Characters', 'Misc1.png'),
    graphic_pos = (0, 64),
)
ogre = Actor(
    char = "0",
    tile_code = 11070,
    color = (63, 127, 63),
    name = "Ogre",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Giant", strength = 21, dexterity = 8, constitution = 15,
                      intelligence = 6, wisdom = 10, charisma = 7, base_na = 5,
                      cr = 3, size = "Large"),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 4),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid1.png'),
    graphic_pos = (16, 16),
)
troll = Actor(
    char = "T",
    tile_code = 11143,
    tile_colors = (colors.green, colors.red),
    color = (0, 127, 0),
    name = "Troll",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Giant", strength = 23, dexterity = 12, constitution = 16,
                      intelligence = 6, wisdom = 12, charisma = 6, base_na = 5, cr = 5,
                      size = "Large", full_attack = [['S', 'claws', 1, 6],['S', 'claws', 1, 6],
                    ['P', 'bites', 1, 6]]),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 6),
    graphic = os.path.join('Dawnlike', 'Characters', 'Undead0.png'),
    graphic_pos = (7*16, 0),
)
ettin = Actor(
    char = "E",
    tile_code = 11075,
    color = (100, 100, 100),
    tile_colors = (colors.white, colors.black),
    name = "Ettin",
    ai_cls = RangedEnemy,
    battler = Battler(hit_dice = "Giant", strength = 23, dexterity = 8, constitution = 15,
                      intelligence = 6, wisdom = 10, charisma = 11, base_na = 7, cr = 6,
                      size = "Large", combat_mode = "Ranged"),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 10),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid0.png'),
    graphic_pos = (6*16, 0),
)
manticore = Actor(
    char = "M",
    tile_code = 11038,
    color = colors.white,
    tile_colors = (colors.white, colors.black),
    name = "Manticore",
    ai_cls = RangedEnemy,
    battler = Battler(hit_dice = "Magical Beast", strength = 20, dexterity = 15, constitution = 19,
                      intelligence = 7, wisdom = 12, charisma = 9, base_na = 6, cr = 5, size = "Large",
                      full_attack = [['P', 'claws', 2, 4], ['P', 'claws', 2, 4], ['S', 'bites', 1, 8]],
                      full_ranged_attack = [['S', 'spikes', 1, 8], ['S', 'spikes', 1, 8], ['S', 'spikes', 1, 8], ['S', 'spikes', 1, 8], ['S', 'spikes', 1, 8], ['S', 'spikes', 1, 8]],
                      combat_mode = "Ranged"),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 6),
    graphic = os.path.join('Dawnlike', 'Characters', 'Quadraped0.png'),
    graphic_pos = (7*16, 0),
)
hill_giant = Actor(
    char = "H",
    tile_code = 11075,
    color = (100, 100, 100),
    tile_colors =(colors.white, colors.black),
    name = "Hill Giant",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Giant", strength = 25, dexterity = 8, constitution = 19,
                      intelligence = 6, wisdom = 10, charisma = 7, base_na = 9, cr = 7, size = "Large",
                      full_attack = [['P', 'slams', 1, 4],['P', 'slams', 1, 4]]), 
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 12),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid0.png'),
    graphic_pos = (7*16, 0),
)
fire_giant = Actor(
    char = "H",
    tile_code = 11075,
    color = colors.red,
    tile_colors =(colors.red, colors.black),
    name = "Fire Giant",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Giant", strength = 31, dexterity = 9, constitution = 21,
                      intelligence = 10, wisdom = 14, charisma = 11, base_na = 8, cr = 10, size = "Large",
                      full_attack = [['P', 'slams', 1, 4],['P', 'slams', 1, 4]]), 
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 15),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid0.png'),
    graphic_pos = (32, 16),
)
frost_giant = Actor(
    char = "H",
    tile_code = 11075,
    color = colors.blue,
    tile_colors =(colors.blue, colors.black),
    name = "Frost Giant",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Giant", strength = 29, dexterity = 9, constitution = 21,
                      intelligence = 10, wisdom = 14, charisma = 11, base_na = 9, cr = 9, size = "Large",
                      full_attack = [['P', 'slams', 1, 4],['P', 'slams', 1, 4]]), 
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 14),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid0.png'),
    graphic_pos = (64, 0),
)
human_skeleton = Actor(
    char = "u",
    tile_code = 11420,
    color = (255, 255, 255),
    name = "Human Skeleton",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Undead", strength = 13, dexterity = 13, constitution = 10,
                     intelligence = 10, wisdom = 10, charisma = 1, base_na = 2, cr = 0.4,
                     full_attack = [['P', 'claws', 1, 4], ['P', 'claws', 1, 4]]),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_level = 1),
    graphic = os.path.join('Dawnlike', 'Characters', 'Undead0.png'),
    graphic_pos = (0, 2*16),
)
boar = Actor(
    char = "b",
    tile_code = 11780,
    color = (100, 0, 0),
    name = "Boar",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 15, dexterity = 10, constitution = 17,
                      intelligence = 2, wisdom = 13, charisma = 4, base_na = 6, cr = 2,
                      full_attack = [['2H', 'gores', 1, 4]]),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 3),
    graphic = os.path.join('Dawnlike', 'Characters', 'Quadraped0.png'),
    graphic_pos = (48, 0),
)
bison = Actor(
    char = "b",
    tile_code = 11554,
    color = (80, 50, 0),
    name = "Bison",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 22, dexterity = 10, constitution = 16,
                      intelligence = 2, wisdom = 11, charisma = 4, base_na = 4, cr = 2,
                      full_attack = [['2H', 'gores', 1, 8]], size = "Large"),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 5),
    graphic = os.path.join('Dawnlike', 'Characters', 'Quadraped0.png'),
    graphic_pos = (48, 16),
)
camel = Actor(
    char = "c",
    tile_code = 11217,
    tile_colors = (colors.red, colors.brown),
    color = (100, 120, 0),
    name = "Camel",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 18, dexterity = 16, constitution = 14,
                      intelligence = 2, wisdom = 11, charisma = 4, base_na = 1, cr = 1,
                      full_attack = [['S', 'bites', 1, 4]], size = "Large"),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 3),
    graphic = os.path.join('Dawnlike', 'Characters', 'Quadraped0.png'),
    graphic_pos = (6*16, 16),
)
crocodile = Actor(
    char = "c",
    tile_code = 11187,
    color = (0, 0, 190),
    name = "Crocodile",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 19, dexterity = 12, constitution = 17,
                      intelligence = 1, wisdom = 12, charisma = 2, base_na = 4, cr = 2,
                      full_attack = [['2H', 'tail slaps', 1, 12]]),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 3),
    graphic = os.path.join('Dawnlike', 'Characters', 'Reptile0.png'),
    graphic_pos = (16, 8*16),
)
hawk = Actor(
    char = "h",
    tile_code = 11013,
    color = (0, 160, 0),
    name = "Hawk",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 6, dexterity = 17, constitution = 10,
                      intelligence = 2, wisdom = 14, charisma = 6, base_na = 2, cr = 0.4,
                      full_attack = [['P', 'rakes', 1, 4]], size = "Tiny",
                      combat_feats = {"Weapon Finesse": 1}),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 1),
    graphic = os.path.join('Dawnlike', 'Characters', 'Avian0.png'),
    graphic_pos = (0, 32),
)
hyena = Actor(
    char = "h",
    tile_code = 10955,
    color = (0, 50, 150),
    name = "Hyena",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 14, dexterity = 15, constitution = 15,
                      intelligence = 2, wisdom = 13, charisma = 6, base_na = 2, cr = 1,
                      full_attack = [['2H', 'bites', 1, 6]]),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 2),
    graphic = os.path.join('Dawnlike', 'Characters', 'Quadraped0.png'),
    graphic_pos = (32, 0),
)
snake = Actor(
    char = "s",
    tile_code = 11098,
    color = (0, 0, 190),
    name = "Snake",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 17, dexterity = 17, constitution = 13,
                      intelligence = 1, wisdom = 12, charisma = 2, base_na = 2, cr = 2,
                      full_attack = [['2H', 'bites', 1, 3]]),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 3),
    graphic = os.path.join('Dawnlike', 'Characters', 'Reptile0.png'),
    graphic_pos = (7*16, 64),
)
wolf = Actor(
    char = "d",
    tile_code = 10959,
    color = (100, 100, 0),
    name = "Wolf",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Animal", strength = 13, dexterity = 15, constitution = 15,
                      intelligence = 2, wisdom = 12, charisma = 6, base_na = 2, cr = 1,
                      full_attack = [['2H', 'bites', 1, 6]]),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 2),
    graphic = os.path.join('Dawnlike', 'Characters', 'Dog0.png'),
    graphic_pos = (0, 16),
)
celestial_badger = Actor(
    char = "b",
    tile_code = 10959,
    tile_colors = (colors.brown, colors.white),
    color = colors.brown,
    name = "Celestial Badger",
    ai_cls = SummonedAlly,
    battler = Battler(hit_dice = "Magical Beast", strength = 8, dexterity = 17, constitution = 15,
                      intelligence = 3, wisdom = 12, charisma = 6, base_na = 1, cr = 0.5,
                      full_attack = [['P', 'claws', 1, 2],['P', 'claws', 1, 2],['S', 'bites', 1, 3]],
                      combat_feats = {"Weapon Finesse": 1}, size = "Small"),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 1),
    graphic = os.path.join('Dawnlike', 'Characters', 'Dog0.png'),
    graphic_pos = (32, 16),
)
celestial_riding_dog = Actor(
    char = "b",
    tile_code = 10959,
    tile_colors = (colors.brown, colors.white),
    color = colors.brown,
    name = "Celestial Riding Dog",
    ai_cls = SummonedAlly,
    battler = Battler(hit_dice = "Magical Beast", strength = 15, dexterity = 15, constitution = 15,
                      intelligence = 3, wisdom = 12, charisma = 6, base_na = 4, cr = 0.5,
                      full_attack = [['2H', 'bites', 1, 6]],
                      ),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 2),
    graphic = os.path.join('Dawnlike', 'Characters', 'Dog0.png'),
    graphic_pos = (32, 16),
)
celestial_dire_badger = Actor(
    char = "b",
    tile_code = 10959,
    tile_colors = (colors.brown, colors.white),
    color = colors.brown,
    name = "Celestial Dire Badger",
    ai_cls = SummonedAlly,
    battler = Battler(hit_dice = "Magical Beast", strength = 14, dexterity = 17, constitution = 19,
                      intelligence = 3, wisdom = 12, charisma = 10, base_na = 3, cr = 2,
                      full_attack = [['P', 'claws', 1, 4],['P', 'claws', 1, 4],['S', 'bites', 1, 6]],
                      combat_feats = {"Toughness": 1}),
    inventory = Inventory(capacity = 0),
    equipment = Equipment(),
    level = Level(current_level = 3),
    graphic = os.path.join('Dawnlike', 'Characters', 'Dog0.png'),
    graphic_pos = (32, 16),
)   
scroll_of_town_portal = Item(
    char = "~",
    tile_code = 10127,
    color = colors.green,
    name = "Scroll of Town Portal",
    consumable = consumable.TownPortalConsumable(),
    equippable = None,
    gold_value = 50,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (0, 0),
)
confusion_scroll = Item(
    char = "~",
    tile_code = 10127,
    color = (207, 63, 255),
    name = "Confusion Scroll",
    consumable = consumable.ConfusionConsumable(number_of_turns = 10),
    equippable = None,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (0, 16),
)
fireball_scroll = Item(
    char = "~",
    tile_code = 10126,
    color = (255, 0, 0),
    name = "Fireball Scroll",
    consumable = consumable.FireballDamageConsumable(damage = 25, radius = 3),
    equippable = None,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (16, 0),
)
cure_light_wounds_potion = Item(
    char = "!",
    tile_code = 10161,
    color = (127, 0, 255),
    name = "Potion of Cure Light Wounds",
    consumable = consumable.HealingConsumable(num_dice = 1, size_dice = 8, bonus = 1),
    equippable = None,
    gold_value = 50,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Potion.png'),
    graphic_pos = (0, 0),
)
cure_moderate_wounds_potion = Item(
    char = "!",
    tile_code = 10161,
    color = (97, 0, 255),
    name = "Potion of Cure Moderate Wounds",
    consumable = consumable.HealingConsumable(num_dice = 2, size_dice = 8, bonus = 3),
    equippable = None,
    gold_value = 300,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Potion.png'),
    graphic_pos = (0, 16),
)
cure_serious_wounds_potion = Item(
    char = "!",
    tile_code = 10161,
    color = (60, 0, 255),
    name = "Potion of Cure Serious Wounds",
    consumable = consumable.HealingConsumable(num_dice = 3, size_dice = 8, bonus = 5),
    equippable = None,
    gold_value = 750,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Potion.png'),
    graphic_pos = (16, 0),
)
cure_critical_wounds_potion = Item(
    char = "!",
    tile_code = 10161,
    color = (30, 0, 255),
    name = "Potion of Cure Critical Wounds",
    consumable = consumable.HealingConsumable(num_dice = 4, size_dice = 8, bonus = 7),
    equippable = None,
    gold_value = 1400,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Potion.png'),
    graphic_pos = (16, 16),
)
tome_of_str_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Strength +5",
    consumable = consumable.StatTomeConsumable(stat = "str", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
tome_of_dex_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Dexterity +5",
    consumable = consumable.StatTomeConsumable(stat = "dex", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
tome_of_con_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Constitution +5",
    consumable = consumable.StatTomeConsumable(stat = "con", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
tome_of_int_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Intelligence +5",
    consumable = consumable.StatTomeConsumable(stat = "int", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
tome_of_wis_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Wisdom +5",
    consumable = consumable.StatTomeConsumable(stat = "wis", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
tome_of_cha_plus_five = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Tome of Charisma +5",
    consumable = consumable.StatTomeConsumable(stat = "cha", bonus = 5),
    equippable = None,
    gold_value = 137500,
    can_stack = True,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (32, 32),
)
lightning_scroll = Item(
    char = "~",
    tile_code = 10125,
    color = (255, 255, 0),
    name = "Lightning Scroll",
    consumable = consumable.LightningDamageConsumable(damage = 40, maximum_range = 5),
    equippable = None,
    graphic = os.path.join('Dawnlike', 'Items', 'Scroll.png'),
    graphic_pos = (64, 0),
)
splint_mail = Item(
    char = "]",
    tile_code = 10309,
    color = (0, 0, 190),
    tile_colors = (colors.white, colors.black),
    name = "Splint Mail",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 7, max_dex_bonus = 0),
    gold_value = 200,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (32, 5*16),
)
chain_shirt = Item(
    char = "]",
    tile_code = 10314,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "Chain Shirt",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 4, max_dex_bonus = 4),
    gold_value = 100,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (4*16, 6*16),
)
chain_shirt_masterwork = Item(
    char = "]",
    tile_code = 10314,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "Masterwork Chain Shirt",
    base_name = "Chain Shirt",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 4, max_dex_bonus = 4,
                            masterwork = True),
    gold_value = 250,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (4*16, 6*16),
)
chain_shirt_plus_one = Item(
    char = "]",
    tile_code = 10314,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "+1 Chain Shirt",
    base_name = "Chain Shirt",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 4, max_dex_bonus = 4,
                            enhance_armor_bonus = 1),
    gold_value = 1250,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (4*16, 6*16),
)
breastplate = Item(
    char = "]",
    tile_code = 10307,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "Breastplate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 6, max_dex_bonus = 3),
    gold_value = 200,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 5*16),
)
breastplate_masterwork = Item(
    char = "]",
    tile_code = 10307,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "Masterwork Breastplate",
    base_name = "Breastplate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 6, max_dex_bonus = 3,
                            masterwork = True),
    gold_value = 350,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 5*16),
)
breastplate_plus_one = Item(
    char = "]",
    tile_code = 10307,
    color = (0, 0, 150),
    tile_colors = (colors.white, colors.black),
    name = "+1 Breastplate",
    base_name = "Breastplate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 6, max_dex_bonus = 3,
                            enhance_armor_bonus = 1),
    gold_value = 1350,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 5*16),
)
hide_armor = Item(
    char = "]",
    tile_code = 10302,
    color = (100, 100, 100),
    tile_colors = (colors.white, colors.black),
    name = "Hide Armor",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 3, max_dex_bonus = 4),
    gold_value = 15,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (16, 7*16),
)
long_sword = Item(
    char = "/",
    tile_code = 10355,
    color = (255, 255, 255),
    tile_colors = (colors.white, colors.black),
    name = "Long Sword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 8, damage_name = "slashes",
                            crit_needs = 19),
    gold_value = 15,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (0, 16),
)
scimitar = Item(
    char = "/",
    tile_code = 10344,
    color = (255, 255, 255),
    tile_colors = (colors.white, colors.black),
    name = "Scimitar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 6, damage_name = "slashes",
                            crit_needs = 18),
    gold_value = 15,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (4*16, 16),
)
scimitar_masterwork = Item(
    char = "/",
    tile_code = 10344,
    color = (255, 255, 255),
    tile_colors = (colors.white, colors.black),
    name = "Masterwork Scimitar",
    base_name = "Scimitar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 6, masterwork = True,
                            damage_name = "slashes", crit_needs = 18),
    gold_value = 315,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (4*16, 16),
)
scimitar_plus_one = Item(
    char = "/",
    tile_code = 10344,
    color = (255, 255, 255),
    tile_colors = (colors.white, colors.black),
    name = "+1 Scimitar",
    base_name = "Scimitar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 6, enhance_melee_bonus = 1,
                            damage_name = "slashes", crit_needs = 18),
    gold_value = 2315,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (4*16, 16),
)
dwarven_waraxe = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, damage_name = "slashes",
                            crit_mult = 3),
    gold_value = 30,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_masterwork = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "Masterwork Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, masterwork = True,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_plus_one = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "+1 Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 1,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 2330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_plus_two = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "+2 Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 2,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 8330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_plus_three = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "+3 Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 3,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 18330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_plus_four = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "+4 Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 4,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 32330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
dwarven_waraxe_plus_five = Item(
    char = "/",
    tile_code = 10367,
    color = (150, 150, 150),
    name = "+5 Dwarven Waraxe",
    base_name = "Dwarven Waraxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 5,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 50330,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greatclub = Item(
    char = "/",
    tile_code = 10241,
    color = (150, 150, 150),
    name = "Greatclub",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, damage_name = "crushes"),
    gold_value = 5,
    graphic = os.path.join('Dawnlike', 'Items', 'ShortWep.png'),
    graphic_pos = (16, 2*16),
)
greatclub_masterwork = Item(
    char = "/",
    tile_code = 10241,
    color = (150, 150, 150),
    name = "Masterwork Greatclub",
    base_name = "Greatclub",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, masterwork = True,
                            damage_name = "crushes"),
    gold_value = 305,
    graphic = os.path.join('Dawnlike', 'Items', 'ShortWep.png'),
    graphic_pos = (16, 2*16),
)
greatclub_plus_one = Item(
    char = "/",
    tile_code = 10241,
    color = (150, 150, 150),
    name = "+1 Greatclub",
    base_name = "Greatclub",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 10, enhance_melee_bonus = 1,
                            damage_name = "crushes"),
    gold_value = 2305,
    graphic = os.path.join('Dawnlike', 'Items', 'ShortWep.png'),
    graphic_pos = (16, 2*16),
)
javelin = Item(
    char = "/",
    tile_code = 10433,
    color = (100, 100, 100),
    name = "Javelin",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 6, damage_name = "pierces"),
    gold_value = 1,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (5*16, 2*16),
)
falchion = Item(
    char = "/",
    tile_code = 10349,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Falchion",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 4, damage_name = "slashes",
                            crit_needs = 18),
    gold_value = 75,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (3*16, 16),
)
falchion_masterwork = Item(
    char = "/",
    tile_code = 10349,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Masterwork Falchion",
    base_name = "Falchion",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 4, masterwork = True,
                            damage_name = "slashes", crit_needs = 18),
    gold_value = 375,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (3*16, 16),
)
falchion_plus_one = Item(
    char = "/",
    tile_code = 10349,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+1 Falchion",
    base_name = "Falchion",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 4, enhance_melee_bonus = 1,
                            damage_name = "slashes", crit_needs = 18),
    gold_value = 2375,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (3*16, 16),
)
greataxe = Item(
    char = "/",
    tile_code = 10374,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Greataxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 12, damage_name = "slashes",
                            crit_mult = 3),
    gold_value = 20,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greataxe_masterwork = Item(
    char = "/",
    tile_code = 10374,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Masterwork Greataxe",
    base_name = "Greataxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 12, masterwork = True,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 320,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greataxe_plus_one = Item(
    char = "/",
    tile_code = 10374,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+1 Greataxe",
    base_name = "Greataxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 12, enhance_melee_bonus = 1,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 2320,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greataxe_plus_two = Item(
    char = "/",
    tile_code = 10374,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+2 Greataxe",
    base_name = "Greataxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 12, enhance_melee_bonus = 2,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 8320,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greataxe_plus_three = Item(
    char = "/",
    tile_code = 10374,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+3 Greataxe",
    base_name = "Greataxe",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 12, enhance_melee_bonus = 3,
                            damage_name = "slashes", crit_mult = 3),
    gold_value = 18320,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 4*16),
)
greatsword = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, damage_name = "slashes",
                            crit_needs = 19),
    gold_value = 50,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_masterwork = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "Masterwork Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, masterwork = True,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_plus_one = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+1 Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, enhance_melee_bonus = 1,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 2350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_plus_two = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+2 Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, enhance_melee_bonus = 2,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 8350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_plus_three = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+3 Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, enhance_melee_bonus = 3,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 18350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_plus_four = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+4 Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, enhance_melee_bonus = 4,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 32350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
greatsword_plus_five = Item(
    char = "/",
    tile_code = 10347,
    tile_colors = (colors.white, colors.black),
    color = (180, 50, 0),
    name = "+5 Greatsword",
    base_name = "Greatsword",
    consumable = None,
    equippable = Equippable(EquipmentSlots.TWO_HAND, weapon_num_dice = 2,
                            weapon_size_dice = 6, enhance_melee_bonus = 5,
                            damage_name = "slashes", crit_needs = 19),
    gold_value = 50350,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (16, 16),
)
morningstar = Item(
    char = ";",
    tile_code = 10360,
    color = (0, 100, 15),
    name = "Morningstar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 8, damage_name = "bashes"),
    gold_value = 8,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (6*16, 0),
)
morningstar_masterwork = Item(
    char = ";",
    tile_code = 10360,
    color = (0, 100, 15),
    name = "Masterwork Morningstar",
    base_name = "Morningstar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 8, masterwork = True,
                            damage_name = "bashes"),
    gold_value = 308,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (6*16, 0),
)
morningstar_plus_one = Item(
    char = ";",
    tile_code = 10360,
    color = (0, 100, 15),
    name = "+1 Morningstar",
    base_name = "Morningstar",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MAIN_HAND, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_melee_bonus = 1,
                            damage_name = "bashes"),
    gold_value = 2308,
    graphic = os.path.join('Dawnlike', 'Items', 'LongWep.png'),
    graphic_pos = (6*16, 0),
)
composite_long_bow = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 180),
    name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, damage_name = "pierces",
                            crit_mult = 3),
    gold_value = 100,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_masterwork = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "Masterwork Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, masterwork = True,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_plus_one = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "+1 Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_ranged_bonus = 1,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 2400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_plus_two = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "+2 Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_ranged_bonus = 2,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 8400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_plus_three = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "+3 Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_ranged_bonus = 3,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 18400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_plus_four = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "+4 Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_ranged_bonus = 4,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 32400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
composite_long_bow_plus_five = Item(
    char = "W",
    tile_code = 10377,
    color = (0, 0, 150),
    name = "+5 Composite Long Bow",
    base_name = "Composite Long Bow",
    consumable = None,
    equippable = Equippable(EquipmentSlots.RANGED, weapon_num_dice = 1,
                            weapon_size_dice = 8, enhance_ranged_bonus = 5,
                            damage_name = "pierces", crit_mult = 3),
    gold_value = 50400,
    graphic = os.path.join('Dawnlike', 'Items', 'Ammo.png'),
    graphic_pos = (16, 16),
)
buckler = Item(
    char = "[",
    tile_code = 10279,
    color = (0, 50, 150),
    name = "Buckler",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1),
    gold_value = 15,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (5*16, 0),
)
buckler_masterwork = Item(
    char = "[",
    tile_code = 10279,
    color = (0, 50, 150),
    name = "Masterwork Buckler",
    base_name = "Buckler",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            masterwork = True),
    gold_value = 165,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (5*16, 0),
)
buckler_plus_one = Item(
    char = "[",
    tile_code = 10279,
    color = (0, 50, 150),
    name = "+1 Buckler",
    base_name = "Buckler",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            enhance_shield_bonus = 1),
    gold_value = 1165,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (5*16, 0),
)
light_shield = Item(
    char = "[",
    tile_code = 10277,
    color = (0, 0, 180),
    name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1),
    gold_value = 9,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
light_shield_masterwork = Item(
    char = "[",
    tile_code = 10277,
    color = (0, 0, 180),
    name = "Masterwork Light Shield",
    base_name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            masterwork = True),
    gold_value = 159,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
light_shield_plus_one = Item(
    char = "[",
    tile_code = 10277,
    color = (0, 0, 180),
    name = "+1 Light Shield",
    base_name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            enhance_shield_bonus = 1),
    gold_value = 1159,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
mithril_light_shield = Item(
    char = "[",
    tile_code = 10277,
    color = colors.blue,
    name = "Mithril Light Shield",
    base_name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            masterwork = True),
    gold_value = 1009,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
mithril_light_shield_plus_one = Item(
    char = "[",
    tile_code = 10277,
    color = colors.blue,
    name = "+1 Mithril Light Shield",
    base_name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 1,
                            enhance_shield_bonus = 1),
    gold_value = 2009,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
animated_mithril_light_shield_plus_one = Item(
    char = "[",
    tile_code = 10277,
    color = colors.blue,
    name = "+1 Animated Mithril Light Shield",
    base_name = "Light Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 1,
                            enhance_shield_bonus = 1),
    gold_value = 10009,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (16, 0),
)
heavy_shield = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2),
    gold_value = 20,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_masterwork = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "Masterwork Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            masterwork = True),
    gold_value = 170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_plus_one = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "+1 Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            enhance_shield_bonus = 1),
    gold_value = 1170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_plus_two = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "+2 Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            enhance_shield_bonus = 2),
    gold_value = 4170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_plus_three = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "+3 Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            enhance_shield_bonus = 3),
    gold_value = 9170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_plus_four = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "+4 Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            enhance_shield_bonus = 4),
    gold_value = 16170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
heavy_shield_plus_five = Item(
    char = "[",
    tile_code = 10278,
    color = (0, 0, 255),
    name = "+5 Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.OFF_HAND, base_shield_bonus = 2,
                            enhance_shield_bonus = 5),
    gold_value = 25170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
animated_heavy_shield_plus_one = Item(
    char = "[",
    tile_code = 10278,
    color = (255, 0, 0),
    name = "+1 Animated Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 2,
                            enhance_shield_bonus = 1),
    gold_value = 9170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
animated_heavy_shield_plus_two = Item(
    char = "[",
    tile_code = 10278,
    color = (255, 0, 0),
    name = "+2 Animated Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 2,
                            enhance_shield_bonus = 2),
    gold_value = 16170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
animated_heavy_shield_plus_three = Item(
    char = "[",
    tile_code = 10278,
    color = (255, 0, 0),
    name = "+3 Animated Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 2,
                            enhance_shield_bonus = 3),
    gold_value = 25170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
animated_heavy_shield_plus_four = Item(
    char = "[",
    tile_code = 10278,
    color = (255, 0, 0),
    name = "+4 Animated Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 2,
                            enhance_shield_bonus = 4),
    gold_value = 36170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
animated_heavy_shield_plus_five = Item(
    char = "[",
    tile_code = 10278,
    color = (255, 0, 0),
    name = "+5 Animated Heavy Shield",
    base_name = "Heavy Shield",
    consumable = None,
    equippable = Equippable(EquipmentSlots.MISC, base_shield_bonus = 2,
                            enhance_shield_bonus = 5),
    gold_value = 49170,
    graphic = os.path.join('Dawnlike', 'Items', 'Shield.png'),
    graphic_pos = (4*16, 0),
)
half_plate = Item(
    char = "]",
    tile_code = 10315,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 220),
    name = "Half Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 8, max_dex_bonus = 0),
    gold_value = 600,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 16),
)
full_plate = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1),
    gold_value = 1500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
full_plate_plus_one = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "+1 Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1,
                            enhance_armor_bonus = 1),
    gold_value = 2650,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
full_plate_plus_two = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "+2 Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1,
                            enhance_armor_bonus = 2),
    gold_value = 5650,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
full_plate_plus_three = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "+3 Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1,
                            enhance_armor_bonus = 3),
    gold_value = 10650,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
full_plate_plus_four = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "+4 Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1,
                            enhance_armor_bonus = 4),
    gold_value = 17650,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
full_plate_plus_five = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.white, colors.black),
    color = (0, 0, 255),
    name = "+5 Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 1,
                            enhance_armor_bonus = 5),
    gold_value = 26650,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (7*16, 0),
)
mithril_full_plate = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            masterwork = True),
    gold_value = 10500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
mithril_full_plate_plus_one = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "+1 Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            enhance_armor_bonus = 1),
    gold_value = 11500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
mithril_full_plate_plus_two = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "+2 Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            enhance_armor_bonus = 2),
    gold_value = 14500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
mithril_full_plate_plus_three = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "+3 Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            enhance_armor_bonus = 3),
    gold_value = 19500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
mithril_full_plate_plus_four = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "+4 Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            enhance_armor_bonus = 4),
    gold_value = 26500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
mithril_full_plate_plus_five = Item(
    char = "]",
    tile_code = 10316,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "+5 Mithril Full Plate",
    base_name = "Full Plate",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 9, max_dex_bonus = 3,
                            enhance_armor_bonus = 5),
    gold_value = 34500,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (5*16, 0),
)
studded_leather = Item(
    char = "]",
    tile_code = 10303,
    color = (0, 0, 120),
    name = "Studded Leather",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 3, max_dex_bonus = 5),
    gold_value = 25,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
studded_leather_masterwork = Item(
    char = "]",
    tile_code = 10303,
    color = (0, 0, 120),
    name = "Masterwork Studded Leather",
    base_name = "Studded Leather",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 3, max_dex_bonus = 5,
                            masterwork = True),
    gold_value = 175,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
studded_leather_plus_one = Item(
    char = "]",
    tile_code = 10303,
    color = (0, 0, 120),
    name = "Studded Leather",
    base_name = "Studded Leather",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 3, max_dex_bonus = 5,
                            enhance_armor_bonus = 1),
    gold_value = 1175,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
leather_armor = Item(
    char = "]",
    tile_code = 10304,
    color = (0, 0, 60),
    name = "Leather Armor",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 2, max_dex_bonus = 6),
    gold_value = 10,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
leather_armor_masterwork = Item(
    char = "]",
    tile_code = 10304,
    color = (0, 0, 60),
    name = "Leather Armor",
    base_name = "Masterwork Leather Armor",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 2, max_dex_bonus = 6,
                            masterwork = True),
    gold_value = 160,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
leather_armor_plus_one = Item(
    char = "]",
    tile_code = 10304,
    color = (0, 0, 60),
    name = "+1 Leather Armor",
    base_name = "Leather Armor",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 2, max_dex_bonus = 6,
                            enhance_armor_bonus = 1),
    gold_value = 1160,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (0, 7*16),
)
spellthief_armor = Item(
    char = "]",
    tile_code = 10314,
    color = (255, 0, 0),
    name = "SpellThief Armor",
    base_name = "Chain Shirt",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BODY, base_armor_bonus = 4, max_dex_bonus = 12,
                            enhance_armor_bonus = 1),
    gold_value = 26100,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (4*16, 7*16),
)
ring_of_prot_plus_one = Item(
    char = "*",
    tile_code = 10132,
    color = colors.white,
    tile_colors = (colors.red, colors.white),
    name = "Ring of Protection + 1",
    consumable = None,
    equippable = Equippable(EquipmentSlots.LRING, deflection_bonus = 1),
    gold_value = 1000,
    graphic = os.path.join('Dawnlike', 'Items', 'Ring.png'),
    graphic_pos = (2*16, 0),
)
ring_of_prot_plus_two = Item(
    char = "*",
    tile_code = 10132,
    color = colors.white,
    tile_colors = (colors.red, colors.white),
    name = "Ring of Protection + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.LRING, deflection_bonus = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Ring.png'),
    graphic_pos = (2*16, 0),
)
ring_of_prot_plus_three = Item(
    char = "*",
    tile_code = 10132,
    color = colors.white,
    tile_colors = (colors.red, colors.white),
    name = "Ring of Protection + 3",
    consumable = None,
    equippable = Equippable(EquipmentSlots.LRING, deflection_bonus = 3),
    gold_value = 9000,
    graphic = os.path.join('Dawnlike', 'Items', 'Ring.png'),
    graphic_pos = (2*16, 0),
)
ring_of_prot_plus_four = Item(
    char = "*",
    tile_code = 10132,
    color = colors.white,
    tile_colors = (colors.red, colors.white),
    name = "Ring of Protection + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.LRING, deflection_bonus = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Ring.png'),
    graphic_pos = (2*16, 0),
)
ring_of_prot_plus_five = Item(
    char = "*",
    tile_code = 10132,
    color = colors.white,
    tile_colors = (colors.red, colors.white),
    name = "Ring of Protection + 5",
    consumable = None,
    equippable = Equippable(EquipmentSlots.LRING, deflection_bonus = 5),
    gold_value = 25000,
    graphic = os.path.join('Dawnlike', 'Items', 'Ring.png'),
    graphic_pos = (2*16, 0),
)
amulet_of_na_plus_one = Item(
    char = "*",
    tile_code = 10227,
    color = colors.white,
    name = "Amulet of Natural Armor + 1",
    consumable = None,
    equippable = Equippable(EquipmentSlots.NECK, enhance_na_bonus = 1),
    gold_value = 1000,
    graphic = os.path.join('Dawnlike', 'Items', 'Amulet.png'),
    graphic_pos = (0, 16),
)
amulet_of_na_plus_two = Item(
    char = "*",
    tile_code = 10227,
    color = colors.white,
    name = "Amulet of Natural Armor + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.NECK, enhance_na_bonus = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Amulet.png'),
    graphic_pos = (0, 16),
)
amulet_of_na_plus_three = Item(
    char = "*",
    tile_code = 10227,
    color = colors.white,
    name = "Amulet of Natural Armor + 3",
    consumable = None,
    equippable = Equippable(EquipmentSlots.NECK, enhance_na_bonus = 3),
    gold_value = 9000,
    graphic = os.path.join('Dawnlike', 'Items', 'Amulet.png'),
    graphic_pos = (0, 16),
)
amulet_of_na_plus_four = Item(
    char = "*",
    tile_code = 10227,
    color = colors.white,
    name = "Amulet of Natural Armor + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.NECK, enhance_na_bonus = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Amulet.png'),
    graphic_pos = (0, 16),
)
amulet_of_na_plus_five = Item(
    char = "*",
    tile_code = 10227,
    color = colors.white,
    name = "Amulet of Natural Armor + 5",
    consumable = None,
    equippable = Equippable(EquipmentSlots.NECK, enhance_na_bonus = 5),
    gold_value = 25000,
    graphic = os.path.join('Dawnlike', 'Items', 'Amulet.png'),
    graphic_pos = (0, 16),
)
girdle_of_giant_str_two = Item(
    char = "|",
    tile_code = 10252,
    tile_colors = (colors.red, colors.black),
    color = (255, 255, 255),
    name = "Girdle of Giant Strength + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BELT, enhance_str_bonus  = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (16, 2*16),
)
girdle_of_giant_str_four = Item(
    char = "|",
    tile_code = 10252,
    tile_colors = (colors.red, colors.black),
    color = (255, 255, 255),
    name = "Girdle of Giant Strength + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BELT, enhance_str_bonus  = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (16, 2*16),
)
girdle_of_giant_str_six = Item(
    char = "|",
    tile_code = 10252,
    tile_colors = (colors.red, colors.black),
    color = (255, 255, 255),
    name = "Girdle of Giant Strength + 6",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BELT, enhance_str_bonus  = 6),
    gold_value = 36000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (16, 2*16),
)
belt = Item(
    char = "|",
    tile_code = 10252,
    tile_colors = (colors.white, colors.black),
    color = (255, 255, 255),
    name = "Leather Belt",
    consumable = None,
    equippable = Equippable(EquipmentSlots.BELT),
    gold_value = 0,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (16, 2*16),
)
gloves_of_dexterity_two = Item(
    char = "[",
    tile_code = 10274,
    tile_colors = (colors.green, colors.black),
    color = colors.green,
    name = "Gloves of Dexterity + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HANDS, enhance_dex_bonus = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Glove.png'),
    graphic_pos = (16, 0),
)
gloves_of_dexterity_four = Item(
    char = "[",
    tile_code = 10274,
    tile_colors = (colors.green, colors.black),
    color = colors.green,
    name = "Gloves of Dexterity + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HANDS, enhance_dex_bonus = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Glove.png'),
    graphic_pos = (16, 0),
)
gloves_of_dexterity_six = Item(
    char = "[",
    tile_code = 10274,
    tile_colors = (colors.green, colors.black),
    color = colors.green,
    name = "Gloves of Dexterity + 6",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HANDS, enhance_dex_bonus = 6),
    gold_value = 36000,
    graphic = os.path.join('Dawnlike', 'Items', 'Glove.png'),
    graphic_pos = (16, 0),
)
vest_of_constitution_two = Item(
    char = "&",
    tile_code = 10301,
    tile_colors = (colors.red, colors.black),
    color = colors.red,
    name = "Vest of Constitution + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.SHIRT, enhance_con_bonus = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 7*16),
)
vest_of_constitution_four = Item(
    char = "&",
    tile_code = 10301,
    tile_colors = (colors.red, colors.black),
    color = colors.red,
    name = "Vest of Constitution + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.SHIRT, enhance_con_bonus = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 7*16),
)
vest_of_constitution_six = Item(
    char = "&",
    tile_code = 10301,
    tile_colors = (colors.red, colors.black),
    color = colors.red,
    name = "Vest of Constitution + 6",
    consumable = None,
    equippable = Equippable(EquipmentSlots.SHIRT, enhance_con_bonus = 6),
    gold_value = 36000,
    graphic = os.path.join('Dawnlike', 'Items', 'Armor.png'),
    graphic_pos = (2*16, 7*16),
)
headband_of_intelligence_two = Item(
    char = "&",
    tile_code = 10544,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "Headband of Intelligence + 2",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HEAD, enhance_int_bonus = 2),
    gold_value = 4000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (3*16, 0),
)
headband_of_intelligence_four = Item(
    char = "&",
    tile_code = 10544,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "Headband of Intelligence + 4",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HEAD, enhance_int_bonus = 4),
    gold_value = 16000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (3*16, 0),
)
headband_of_intelligence_six = Item(
    char = "&",
    tile_code = 10544,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "Headband of Intelligence + 6",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HEAD, enhance_int_bonus = 6),
    gold_value = 36000,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (3*16, 0),
)
headband = Item(
    char = "&",
    tile_code = 10544,
    tile_colors = (colors.blue, colors.black),
    color = colors.blue,
    name = "Headband",
    consumable = None,
    equippable = Equippable(EquipmentSlots.HEAD),
    gold_value = 0,
    graphic = os.path.join('Dawnlike', 'Items', 'Tool.png'),
    graphic_pos = (3*16, 0),
)
red_bag = Bag(
    char = "{",
    tile_code = 10544,
    tile_colors = (colors.red, colors.black),
    color = colors.red,
    name = "Red Bag",
    consumable = None,
    equippable = None,
    gold_value = 0,
    bag_inventory = Bag_Inventory(capacity = 26, items = []),
    graphic = os.path.join('Dawnlike', 'Items', 'Chest0.png'),
    graphic_pos = (2*16, 2*16),
)
stairs = Stairs(
    char = ">",
    tile_code = 10027,
    tile_colors = (colors.white, colors.black),
    color = (255, 255, 255),
    name = "Stairs down",
    stairs = 1,
    graphic = os.path.join('Dawnlike', 'Objects', 'Tile.png'),
    graphic_pos = (80, 48),
)
up_stairs = Stairs(
    char = "<",
    tile_code = 10025,
    tile_colors = (colors.white, colors.black),
    color = (255, 255, 255),
    name = "Stairs up",
    stairs = -1,
    graphic = os.path.join('Dawnlike', 'Objects', 'Tile.png'),
    graphic_pos = (64, 48),
)
armor_shop = Shop(
    char = "A",
    color = (255, 255, 255),
    tile_code = 10073,
    tile_colors = (colors.white, colors.black),
    name = "Armor Shop",
    for_sale = [full_plate,full_plate_plus_one, full_plate_plus_three,
                full_plate_plus_five,
                leather_armor, studded_leather, breastplate, splint_mail,
                light_shield, heavy_shield, heavy_shield_masterwork,
                heavy_shield_plus_one, heavy_shield_plus_three, heavy_shield_plus_five,
                animated_heavy_shield_plus_one, animated_heavy_shield_plus_three,
                animated_heavy_shield_plus_five,
                spellthief_armor, mithril_full_plate, mithril_full_plate_plus_one,
                mithril_full_plate_plus_three, mithril_full_plate_plus_five],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (2*16, 6*16),
)
weapon_shop = Shop(
    char = "W",
    color = (255, 255, 255),
    tile_code = 10074,
    tile_colors = (colors.white, colors.black),
    name = "Weapon Shop",
    for_sale = [dwarven_waraxe, dwarven_waraxe_masterwork, dwarven_waraxe_plus_one,
                dwarven_waraxe_plus_two, dwarven_waraxe_plus_three, greatsword,
                greatsword_masterwork, greatsword_plus_one,  greatsword_plus_two,
                greatsword_plus_three, greatsword_plus_four, greatsword_plus_five,
                falchion, long_sword, morningstar, greatclub],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (2*16, 6*16),
)
bow_shop = Shop(
    char = "W",
    color = (255, 255, 0),
    tile_code = 10071,
    tile_colors = (colors.white, colors.black),
    name = "Ranged Shop",
    for_sale = [composite_long_bow, composite_long_bow_masterwork, composite_long_bow_plus_one, 
                composite_long_bow_plus_two, composite_long_bow_plus_three,
                composite_long_bow_plus_four, composite_long_bow_plus_five,
                javelin],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (3*16, 6*16),
)
potion_shop = Shop(
    char = "!",
    color = (255, 255, 255),
    tile_code = 10076,
    tile_colors = (colors.white, colors.black),
    name = "Potion Shop",
    for_sale = [cure_light_wounds_potion, cure_moderate_wounds_potion,
                cure_serious_wounds_potion, cure_critical_wounds_potion],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (5*16, 6*16),
)
jewelry_shop = Shop(
    char = "*",
    color = colors.red,
    tile_code = 10077,
    tile_colors = (colors.white, colors.red),
    name = "Jewelry Shop",
    for_sale = [amulet_of_na_plus_one, amulet_of_na_plus_two, amulet_of_na_plus_three,
                amulet_of_na_plus_four, amulet_of_na_plus_five,
                ring_of_prot_plus_one, ring_of_prot_plus_two, ring_of_prot_plus_three,
                ring_of_prot_plus_four, ring_of_prot_plus_five],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (6*16, 6*16),
)
clothing_shop = Shop(
    char = ";",
    color = colors.white,
    tile_code = 10080,
    tile_colors = (colors.white, colors.black),
    name = "Clothing Shop",
    for_sale = [girdle_of_giant_str_two, girdle_of_giant_str_four, girdle_of_giant_str_six,
                gloves_of_dexterity_two, gloves_of_dexterity_four, gloves_of_dexterity_six,
                vest_of_constitution_two, vest_of_constitution_four, vest_of_constitution_six,
                headband_of_intelligence_two, headband_of_intelligence_four, headband_of_intelligence_six,
                headband, belt],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (4*16, 6*16),
)
misc_shop = Shop(
    char = ";",
    color = colors.white,
    tile_code = 10072,
    tile_colors = (colors.white, colors.black),
    name = "Misc Shop",
    for_sale = [scroll_of_town_portal, spellthief_armor, mithril_light_shield_plus_one,
                animated_mithril_light_shield_plus_one,
                tome_of_str_plus_five, tome_of_dex_plus_five, tome_of_con_plus_five,
                tome_of_int_plus_five, tome_of_wis_plus_five, tome_of_cha_plus_five,
                red_bag],
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (0, 6*16),
)
enchanter = Enchant(
    char = ";",
    color = colors.white,
    tile_code = 10072,
    tile_colors = (colors.white, colors.black),
    name = "Enchanter",
    graphic = os.path.join('Dawnlike', 'Objects', 'Decor0.png'),
    graphic_pos = (6*16, 6*16),
)
dwarf_fighter = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.green),
    color = (255, 255, 255),
    name = "Flint",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Fighter", strength = 18, dexterity = 14, constitution = 16,
                      intelligence = 10, wisdom = 14, charisma = 5,
                      feats_to_take = 2, gold = 1000000),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 50000),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player0.png'),
    graphic_pos = (0, 112),
)
human_fighter = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.green),
    color = (255, 255, 255),
    name = "Sturm",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Fighter", strength = 20, dexterity = 14, constitution = 14,
                      intelligence = 10, wisdom = 10, charisma = 8,
                      feats_to_take = 3, gold = 0),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 0),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player0.png'),
    graphic_pos = (0, 112),
)
orc_barbarian = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.green),
    color = (255, 255, 255),
    name = "Krog",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Barbarian", strength = 22, dexterity = 14, constitution = 14,
                      intelligence = 8, wisdom = 8, charisma = 6,
                      feats_to_take =1, gold = 0),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 0),
    graphic = os.path.join('Dawnlike', 'Characters', 'Humanoid0.png'),
    graphic_pos = (0, 16),
)
human_cleric = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.blue),
    color = (255, 255, 255),
    name = "Palin",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Cleric", strength = 14, dexterity = 12, constitution = 14,
                      intelligence = 10, wisdom = 20, charisma = 10,
                      feats_to_take = 2, gold = 0,
                      spells = {"Cure Light Wounds": 1, "Magic Weapon": 1,
                                "Cure Moderate Wounds": 3}),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 0),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player0.png'),
    graphic_pos = (0, 112),
)
elf_wizard = Actor(
    char = "@",
    tile_code = 10775,
    tile_colors = (colors.white, colors.red),
    color = (255, 255, 255),
    name = "Elbereth",
    ai_cls = HostileEnemy,
    battler = Battler(hit_dice = "Wizard", strength = 8, dexterity = 16, constitution = 14,
                      intelligence = 20, wisdom = 8, charisma = 8,
                      feats_to_take = 1, gold = 0,
                      spells = {"Magic Missile": 1, "Shocking Grasp": 1,
                                "Mage Armor": 1, "Shield": 1, "Magic Weapon": 1,
                                "Summon Monster 1": 1, "Burning Hands": 1,
                                "Ray of Enfeeblement": 1, "Alter Self": 3,
                                "Summon Monster 2": 3, "Scorching Ray": 3,
                                "Summon Monster 3": 5}),
    inventory = Inventory(capacity = 26),
    equipment = Equipment(),
    level = Level(current_xp = 100000),
    graphic = os.path.join('Dawnlike', 'Characters', 'Player0.png'),
    graphic_pos = (0, 112),
)
